using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Backend.TrainingData
{
    public class OrderPlacmentData : IEntityTypeConfiguration<OrderPlacement>
    {
        public void Configure(EntityTypeBuilder<OrderPlacement> builder)
        {
            builder.HasData
            (
                // Orders for Customer 1
                new OrderPlacement {Id = 1, PickUpAddress = "Red Square, 1, Moscow, Russia, 101000", DeliveryUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", PickUpContact = "John Doe", DeliveryContact = "Jane Smith", Description = "Electronics", Status = "Delivered", Price = 300.00m, CreatedAt = new DateTime(2023, 09, 01), ScheduledAt = new DateTime(2023, 9, 2), CompletedOn = new DateTime(2023, 9, 3), CustomerId = 1 },
                new OrderPlacement {Id = 2, PickUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", DeliveryUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", PickUpContact = "John Doe", DeliveryContact = "Alice Brown", Description = "Computers", Status = "In Transit", Price = 500.00m, CreatedAt = new DateTime(2023, 09, 02), ScheduledAt = new DateTime(2023, 9, 4), CompletedOn = new DateTime(2023, 9, 5), CustomerId = 1 },
                new OrderPlacement {Id = 3, PickUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", DeliveryUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", PickUpContact = "John Doe", DeliveryContact = "Bob White", Description = "Accessories", Status = "Pending", Price = 150.00m, CreatedAt = new DateTime(2023, 09, 03), ScheduledAt = new DateTime(2023, 9, 6), CompletedOn = new DateTime(2023, 9, 7), CustomerId = 1 },
                new OrderPlacement {Id = 4, PickUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", DeliveryUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", PickUpContact = "John Doe", DeliveryContact = "Lucy Green", Description = "Furniture", Status = "Cancelled", Price = 600.00m, CreatedAt = new DateTime(2023, 09, 04), ScheduledAt = new DateTime(2023, 9, 7), CompletedOn = new DateTime(2023, 9, 8), CustomerId = 1 },

                // Orders for Customer 2
                new OrderPlacement {Id = 5, PickUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", DeliveryUpAddress = "Red Square, 1, Moscow, Russia, 101000", PickUpContact = "Alice Green", DeliveryContact = "Tom Brown", Description = "Fresh Produce", Status = "Delivered", Price = 200.00m, CreatedAt = new DateTime(2023, 09, 01), ScheduledAt = new DateTime(2023, 9, 2), CompletedOn = new DateTime(2023, 9, 3), CustomerId = 2 },
                new OrderPlacement {Id = 6, PickUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", DeliveryUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", PickUpContact = "Alice Green", DeliveryContact = "Sarah White", Description = "Dairy Products", Status = "In Transit", Price = 300.00m, CreatedAt = new DateTime(2023, 09, 02), ScheduledAt = new DateTime(2023, 9, 4), CompletedOn = new DateTime(2023, 9, 5), CustomerId = 2 },
                new OrderPlacement {Id = 7, PickUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", DeliveryUpAddress = "Red Square, 1, Moscow, Russia, 101000", PickUpContact = "Alice Green", DeliveryContact = "Daniel Black", Description = "Packaged Goods", Status = "Pending", Price = 250.00m, CreatedAt = new DateTime(2023, 09, 03), ScheduledAt = new DateTime(2023, 9, 6), CompletedOn = new DateTime(2023, 9, 7), CustomerId = 2 },
                new OrderPlacement {Id = 8, PickUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", DeliveryUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", PickUpContact = "Alice Green", DeliveryContact = "Emma Red", Description = "Beverages", Status = "Cancelled", Price = 400.00m, CreatedAt = new DateTime(2023, 09, 04), ScheduledAt = new DateTime(2023, 9, 7), CompletedOn = new DateTime(2023, 9, 8), CustomerId = 2 },

                // Orders for Customer 3
                new OrderPlacement {Id = 9, PickUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", DeliveryUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", PickUpContact = "Alice Johnson", DeliveryContact = "Jim Doe", Description = "Fast Food Order", Status = "Delivered", Price = 50.00m, CreatedAt = new DateTime(2023, 09, 01), ScheduledAt = new DateTime(2023, 9, 2), CompletedOn = new DateTime(2023, 9, 3), CustomerId = 3 },
                new OrderPlacement {Id = 10, PickUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", DeliveryUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", PickUpContact = "Alice Johnson", DeliveryContact = "Kate Brown", Description = "Burger Order", Status = "In Transit", Price = 30.00m, CreatedAt = new DateTime(2023, 09, 02), ScheduledAt = new DateTime(2023, 9, 4), CompletedOn = new DateTime(2023, 9, 5), CustomerId = 3 },
                new OrderPlacement {Id = 11, PickUpAddress = "Red Square, 1, Moscow, Russia, 101000", DeliveryUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", PickUpContact = "Alice Johnson", DeliveryContact = "Ben White", Description = "Pizza Order", Status = "Pending", Price = 40.00m, CreatedAt = new DateTime(2023, 09, 03), ScheduledAt = new DateTime(2023, 9, 6), CompletedOn = new DateTime(2023, 9, 7), CustomerId = 3 },
                new OrderPlacement {Id = 12, PickUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", DeliveryUpAddress = "Red Square, 1, Moscow, Russia, 101000", PickUpContact = "Alice Johnson", DeliveryContact = "Beth Green", Description = "Dessert Order", Status = "Cancelled", Price = 20.00m, CreatedAt = new DateTime(2023, 09, 04), ScheduledAt = new DateTime(2023, 9, 7), CompletedOn = new DateTime(2023, 9, 8), CustomerId = 3 },

                // Orders for Customer 4
                new OrderPlacement {Id = 13, PickUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", DeliveryUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", PickUpContact = "John Smith", DeliveryContact = "Alice Johnson", Description = "Books", Status = "Delivered", Price = 25.00m, CreatedAt = new DateTime(2023, 09, 01), ScheduledAt = new DateTime(2023, 9, 2), CompletedOn = new DateTime(2023, 9, 3), CustomerId = 4 },
                new OrderPlacement {Id = 14, PickUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", DeliveryUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", PickUpContact = "John Smith", DeliveryContact = "Bob White", Description = "Textbooks", Status = "In Transit", Price = 45.00m, CreatedAt = new DateTime(2023, 09, 02), ScheduledAt = new DateTime(2023, 9, 4), CompletedOn = new DateTime(2023, 9, 5), CustomerId = 4 },
                new OrderPlacement {Id = 15, PickUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", DeliveryUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", PickUpContact = "John Smith", DeliveryContact = "Charlie Black", Description = "Novels", Status = "Pending", Price = 50.00m, CreatedAt = new DateTime(2023, 09, 03), ScheduledAt = new DateTime(2023, 9, 6), CompletedOn = new DateTime(2023, 9, 7), CustomerId = 4 },
                new OrderPlacement {Id = 16, PickUpAddress = "Red Square, 1, Moscow, Russia, 101000", DeliveryUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", PickUpContact = "John Smith", DeliveryContact = "David Green", Description = "Magazines", Status = "Cancelled", Price = 30.00m, CreatedAt = new DateTime(2023, 09, 04), ScheduledAt = new DateTime(2023, 9, 7), CompletedOn = new DateTime(2023, 9, 8), CustomerId = 4 },

                // Orders for Customer 5
                new OrderPlacement {Id = 17, PickUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", DeliveryUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", PickUpContact = "Emily White", DeliveryContact = "James Black", Description = "Home Goods", Status = "Delivered", Price = 200.00m, CreatedAt = new DateTime(2023, 09, 01), ScheduledAt = new DateTime(2023, 9, 2), CompletedOn = new DateTime(2023, 9, 3), CustomerId = 5 },
                new OrderPlacement {Id = 18, PickUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", DeliveryUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", PickUpContact = "Emily White", DeliveryContact = "Sarah Green", Description = "Furniture", Status = "In Transit", Price = 800.00m, CreatedAt = new DateTime(2023, 09, 02), ScheduledAt = new DateTime(2023, 9, 4), CompletedOn = new DateTime(2023, 9, 5), CustomerId = 5 },
                new OrderPlacement {Id = 19, PickUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", DeliveryUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", PickUpContact = "Emily White", DeliveryContact = "Paul Red", Description = "Kitchenware", Status = "Pending", Price = 150.00m, CreatedAt = new DateTime(2023, 09, 03), ScheduledAt = new DateTime(2023, 9, 6), CompletedOn = new DateTime(2023, 9, 7), CustomerId = 5 },
                new OrderPlacement {Id = 20, PickUpAddress = "Lenina Street, 1, Ufa, Republic of Bashkortostan, Russia, 450000", DeliveryUpAddress = "Red Square, 1, Moscow, Russia, 101000", PickUpContact = "Emily White", DeliveryContact = "Jessica Blue", Description = "Decorations", Status = "Cancelled", Price = 100.00m, CreatedAt = new DateTime(2023, 09, 04), ScheduledAt = new DateTime(2023, 9, 7), CompletedOn = new DateTime(2023, 9, 8), CustomerId = 5 },

                // Orders for Customer 6
                new OrderPlacement {Id = 21, PickUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000t", DeliveryUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", PickUpContact = "Mike Brown", DeliveryContact = "Anna Green", Description = "Gym Equipment", Status = "Delivered", Price = 500.00m, CreatedAt = new DateTime(2023, 09, 01), ScheduledAt = new DateTime(2023, 9, 2), CompletedOn = new DateTime(2023, 9, 3), CustomerId = 6 },
                new OrderPlacement {Id = 22, PickUpAddress = "Palace Square, 2, St. Petersburg, Russia, 191186", DeliveryUpAddress = "Red Square, 1, Moscow, Russia, 101000", PickUpContact = "Mike Brown", DeliveryContact = "Laura Black", Description = "Fitness Apparel", Status = "In Transit", Price = 150.00m, CreatedAt = new DateTime(2023, 09, 02), ScheduledAt = new DateTime(2023, 9, 4), CompletedOn = new DateTime(2023, 9, 5), CustomerId = 6 },
                new OrderPlacement {Id = 23, PickUpAddress = "Red Square, 1, Moscow, Russia, 101000", DeliveryUpAddress = "Minin and Pozharsky Square, 1, Nizhny Novgorod, Russia, 603000", PickUpContact = "Mike Brown", DeliveryContact = "Cathy White", Description = "Health Supplements", Status = "Pending", Price = 300.00m, CreatedAt = new DateTime(2023, 09, 03), ScheduledAt = new DateTime(2023, 9, 6), CompletedOn = new DateTime(2023, 9, 7), CustomerId = 6 },
                new OrderPlacement { Id = 24, PickUpAddress = "Kuibysheva Street, 1, Samara, Russia, 443000", DeliveryUpAddress = "Bauman Street, 1, Kazan, Republic of Tatarstan, Russia, 420111", PickUpContact = "Mike Brown", DeliveryContact = "Sarah Blue", Description = "Yoga Mats", Status = "Cancelled", Price = 100.00m, CreatedAt = new DateTime(2023,09,04), ScheduledAt = new DateTime(2023, 9, 7), CompletedOn = new DateTime(2023, 9, 8), CustomerId = 6 }
        
               );
        }
    }
}
